### ISSUE TITLE
Error: Cannot find module 'request'

### ISSUE THREAD

**Issue by archiolochos** [TheDoudou/homebridge-BoschIndego#1]
i tried your module today and i got the following error. i have no idea how to solve that prolem. maybe it helps you to find a possible bug?

Error: Cannot find module 'request'
Require stack:
- /app/available_modules/1562931482000/homebridge-boschindego/index.js
- /app/index.js

**Comment by TheDoudou** [comment]
You can try
`npm install request --save`

You don't have request module for nodejs.

Next time i add it in project.

(my mower is not working now, i moved)

**Comment by archiolochos** [comment]
that worked. Thanks a lot.

**Comment by mas1978** [comment]
Hello, same topic, but the solution above does not fix the error. I get the following error:

====================
[7/13/2019, 1:39:25 PM] ERROR LOADING PLUGIN homebridge-boschindego:
[7/13/2019, 1:39:25 PM] Error: Cannot find module 'request'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-boschindego/index.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[7/13/2019, 1:39:25 PM] ====================

What can I do? Maybe wrong nodejs version?

Thank you.

**Comment by mas1978** [comment]
P.S:
When I use the save install above, I get the following result:

npm WARN saveError ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.

**Comment by MCLMNN** [comment]
Hello,

i have the same problem with "request". The solution with "npm install request --save" doesn't brought any improvements. I receive the same error as mas1978 got.
Is there a solution, that works?

Thanks.

**Comment by KaiMessner** [comment]
Same problem here. Is there an solution?

**Comment by karlismaj** [comment]
Same here:
[9/20/2020, 2:31:48 PM] ERROR LOADING PLUGIN homebridge-boschindego:
[9/20/2020, 2:31:48 PM] Error: Cannot find module 'request'
Require stack:
- /homebridge/node_modules/homebridge-boschindego/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/api.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-boschindego/index.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)

**Comment by karlismaj** [comment]
> You can try
> `npm install request --save`
> 
> You don't have request module for nodejs.
> 
> Next time i add it in project.
> 
> (my mower is not working now, i moved)

This has worked for me

**Comment by Tech-Nick1** [comment]
The same problem still exists. Also „npm install request --save“ brings no change. Is there a chance that you will revise the plugin?
