### ISSUE TITLE
Accessory 'BoschIndego' was not registered by any plugin

### ISSUE THREAD

**Issue by superpower10** [TheDoudou/homebridge-BoschIndego#2]
Plugin installiert und konfiguriert. Beim Neustart der Hombridge kommt folgende Fehlermeldung und die Homebridge startet nicht:

```
Error: The requested accessory 'BoschIndego' was not registered by any plugin.
    at PluginManager.getPluginForAccessory (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:198:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:345:37
    at Array.forEach (<anonymous>)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:328:29)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:154:12)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
```

**Comment by Tech-Nick1** [comment]
Hattest du zwischenzeitlich eine Lösung gefunden? Es hört sich so an, als würde es an falschen Zugangsdaten zum Bosch smart Gardening liegen
